export interface CompoundMapping {
  excelName: string;
  imageName: string;
  confidence: 'High' | 'Medium' | 'Low';
  notes: string;
}

export const compoundMappings: CompoundMapping[] = [
  { excelName: 'o-Toluic Acid', imageName: 'O-Toluic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: '2,3,4-THBA', imageName: '2,3,4-THBA', confidence: 'High', notes: 'Exact match' },
  { excelName: '2,3,4-TMBA', imageName: '2,3,4-TMBA', confidence: 'High', notes: 'Exact match' },
  { excelName: '2,4,5-TMBA', imageName: '2,4,5-TMBA', confidence: 'High', notes: 'Exact match' },
  { excelName: '2-Hydroxyacetophenone', imageName: '2-Hydroxyacetophenone', confidence: 'High', notes: 'Exact match' },
  { excelName: '2-Methoxy-4-vinylphenol', imageName: '2-M-4-Vinylphenol', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '2-Methoxyacetophenone', imageName: '2-MAcetophenone', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'o-Anisic acid', imageName: '2-MBA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '2-methylbenzaldehyde', imageName: '2-Methylbenzaldehyde', confidence: 'High', notes: 'Case difference' },
  { excelName: '3,4-Dihydroxyphenylacetic acid', imageName: '3,4-DHPAA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '3,5-Dihydroxybenzoic acid', imageName: '3,5-DHBA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '3-Phenylpropanoic acid', imageName: '3-PhenylPropionic Acid', confidence: 'High', notes: 'Propionic vs Propanoic naming' },
  { excelName: 'Genkwanin', imageName: '4, 5-DH-7MFI', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'p-Hydroxyphenylacetic acid', imageName: '4-HPAA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'DL-p-Phenyllactic Acid', imageName: '4-HPhenyllactic Acid', confidence: 'Medium', notes: 'Abbreviation or alternate name used' },
  { excelName: 'DL-p-Phenyllactic Acid', imageName: '4-HPhenyllactic Acid2', confidence: 'Medium', notes: 'Duplicate / alternate variant' },
  { excelName: '4-methylpyrocatechol', imageName: '4-MCA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '4-methylpyrocatechol', imageName: '4-Methylcatechol-1', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'No matching entry', imageName: '4-MPAA', confidence: 'Low', notes: 'No corresponding entry in Excel' },
  { excelName: '4-methylpyrocatechol', imageName: '4-Methylcatechol-1.xlsx (file)', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'Genkwanin', imageName: '4,5-DH-7MFI.xlsx (file)', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '5-Methoxyflavone', imageName: '5-Methoxyflavone', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Formononetin', imageName: '5,7-DH4-MIso (file)', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '6-Hydroxyflavone-β-D-Glucose', imageName: '6-HFlavone-B-D-G (file)', confidence: 'Medium', notes: 'Abbreviation or alternate name used' },
  { excelName: 'Absiscic Acid', imageName: 'Absiscic Acid', confidence: 'High', notes: 'Exact match (spelling variant of Abscisic)' },
  { excelName: 'acacetin', imageName: 'Acacetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Acetaminophen', imageName: 'Acetaminophen', confidence: 'High', notes: 'Exact match' },
  { excelName: 'apigenin', imageName: 'Apigenin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Aspirin', imageName: 'Aspirin', confidence: 'High', notes: 'Exact match' },
  { excelName: 'baicalin', imageName: 'Baicalin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'benzoic acid', imageName: 'Benzoic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'benzophenone', imageName: 'Benzophenone', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Biochanin A', imageName: 'Biochanin A', confidence: 'High', notes: 'Exact match' },
  { excelName: 'No matching entry', imageName: 'CADE', confidence: 'Low', notes: 'No corresponding entry in Excel' },
  { excelName: 'caffeic acid', imageName: 'Caffeic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'CAPE', imageName: 'CAPE', confidence: 'High', notes: 'Exact match (abbreviation)' },
  { excelName: 'catechin', imageName: 'Catechin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Chlorogenic Acid', imageName: 'Chlorogenic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'chrysin', imageName: 'Chrysin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'No matching entry', imageName: 'Coumestrol', confidence: 'Low', notes: 'No corresponding entry in Excel' },
  { excelName: 'Cuminic Acid', imageName: 'Cuminic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'daidzein', imageName: 'Daidzein', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Dibenzyl oxalate', imageName: 'Dibenzyl oxalate', confidence: 'High', notes: 'Exact match' },
  { excelName: 'DL-p-Phenyllactic Acid', imageName: 'DL-p-Hydroxyphenyllactic Acid', confidence: 'Medium', notes: 'Abbreviation or alternate name used' },
  { excelName: 'DL-p-Phenyllactic Acid', imageName: 'DL-p-Phenyllactic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'epigallocatechin', imageName: 'EGC', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: '(-)-epigallocatechin gallate', imageName: 'EGCG', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'Ellagic Acid', imageName: 'Ellagic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'epicatechin', imageName: 'Epicatechin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Eudesmic Acid', imageName: 'Eudesmic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Ferulic Acid', imageName: 'Ferulic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'fisetin', imageName: 'Fisetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'formononetin', imageName: 'Formononetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'galangin', imageName: 'Galangin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'gallic acid', imageName: 'Gallic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'genistein', imageName: 'Genistein', confidence: 'High', notes: 'Case difference' },
  { excelName: 'genistin', imageName: 'Genistin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'gentisic acid', imageName: 'Gentisic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'hesperidin', imageName: 'Hesperidin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'hesperetin', imageName: 'Hesperetin', confidence: 'High', notes: 'Case difference (corrected spelling)' },
  { excelName: 'Homovanillic Acid', imageName: 'Homovanillic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Isoferulic Acid', imageName: 'Isoferulic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Isopseudocumenol', imageName: 'Isopseudocumenol', confidence: 'High', notes: 'Case difference (minor spelling variation)' },
  { excelName: 'isorhamnetin', imageName: 'Isorhamnetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'kaempferol', imageName: 'Kaempferol', confidence: 'High', notes: 'Case difference' },
  { excelName: 'kaempferide', imageName: 'Kaempferide', confidence: 'High', notes: 'Case difference (corrected spelling)' },
  { excelName: 'Kojic Acid', imageName: 'Kojic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'L-β-Phenyllactic Acid', imageName: 'L-Β-Phenyllactic Acid', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'Lepteridine', imageName: 'Lepteridine', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Leptosperine', imageName: 'Leptosperine', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Lumichrome', imageName: 'Lumichrome', confidence: 'High', notes: 'Exact match' },
  { excelName: 'luteolin', imageName: 'Luteolin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'm-coumaric acid', imageName: 'M-Coumaric Acid', confidence: 'High', notes: 'Case difference (m = meta)' },
  { excelName: 'm-hydroxybenzoic acid', imageName: 'M-HBA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'm-Toluic Acid', imageName: 'M-Toluic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Mandelic Acid', imageName: 'Mandelic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'methyl ferulate', imageName: 'Methyl ferulate', confidence: 'High', notes: 'Case difference' },
  { excelName: 'methyl paraben', imageName: 'Methyl paraben', confidence: 'High', notes: 'Case difference' },
  { excelName: 'methyl syringate', imageName: 'Methyl syringate', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Methyl-3,4,5-trimethoxybenzoate', imageName: 'Methyl-3,4,5-TMBenzoate', confidence: 'High', notes: 'Case difference' },
  { excelName: 'myricetin', imageName: 'Myricetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'naringenin', imageName: 'Naringenin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'naringin', imageName: 'Naringin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Neochlorogenic Acid', imageName: 'Neochlorogenic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'o-coumaric acid', imageName: 'O-Coumaric Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'p-anisaldehyde', imageName: 'p-Anisaldehyde', confidence: 'High', notes: 'Case difference' },
  { excelName: 'p-coumaric acid', imageName: 'p-Coumaric Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'p-hydroxybenzoic acid', imageName: 'p-HBA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'p-methoxyphenol', imageName: 'p-MPhenol', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'Phenylacetic Acid', imageName: 'Phenylacetic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Phloretic acid', imageName: 'Phloretic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'pinobanksin', imageName: 'Pinobanksin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'pinocembrin', imageName: 'Pinocembrin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Protocatechualdehyde', imageName: 'Protocatechualdehyde', confidence: 'High', notes: 'Case difference' },
  { excelName: 'protocatechuic acid', imageName: 'Protocatechuic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Pyrocatechol', imageName: 'Pyrocatechol', confidence: 'High', notes: 'Case difference' },
  { excelName: 'quercetin', imageName: 'Quercetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'resorcylic acid', imageName: 'Resorcylic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Rosmarinic Acid', imageName: 'Rosmarinic Acid', confidence: 'High', notes: 'Exact match' },
  { excelName: 'Rutin', imageName: 'Rutin', confidence: 'High', notes: 'Exact match' },
  { excelName: 'sakuranetin', imageName: 'Sakuranetin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'salicylic acid', imageName: 'Salicylic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 'syringic acid', imageName: 'Syringic Acid', confidence: 'High', notes: 'Case difference' },
  { excelName: 't-Chalcone', imageName: 't-Chalcone', confidence: 'High', notes: 'Exact match (t = trans)' },
  { excelName: 't-cinnamic acid', imageName: 't-Cinnamic Acid', confidence: 'High', notes: 'Case difference (t = trans)' },
  { excelName: 'trans-p-coumaric acid methyl ester', imageName: 't-PCME', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'taxifolin', imageName: 'Taxifolin', confidence: 'High', notes: 'Case difference' },
  { excelName: 'Thymol', imageName: 'Thymol', confidence: 'High', notes: 'Exact match' },
  { excelName: 'vanillic acid', imageName: 'VA', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'vanillic acid methyl ester', imageName: 'VAME', confidence: 'High', notes: 'Abbreviation or alternate name used' },
  { excelName: 'Vanillin', imageName: 'Vanillin', confidence: 'High', notes: 'Exact match' },
  { excelName: 'vitexin', imageName: 'vitexin', confidence: 'High', notes: 'Exact match' },
];

// helper lookup
export function getImageNameFromExcel(excelName: string): string | undefined {
  const entry = compoundMappings.find(
    (item) => item.excelName.toLowerCase() === excelName.toLowerCase()
  );
  return entry?.imageName;
}